import type { HexColor } from './types';

export const white: HexColor = '#fff';
export const red: HexColor = '#a15555';
export const rose: HexColor = '#B88787';
export const blush: HexColor = '#e9dedd';
export const buccaneer: HexColor = '#702e2e';
export const thatch: HexColor = '#bd9898';
export const green: HexColor = '#2B8519';
export const grass: HexColor = '#83a57d';
export const shade: HexColor = '#282828';
export const somber: HexColor = '#222';
export const ash: HexColor = '#333';
export const cinder: HexColor = '#444';
export const gray: HexColor = '#888';
export const ivory: HexColor = '#f0f0e0';
export const moonMist: HexColor = '#dad7c7';
export const wood: HexColor = '#594D4C';
export const cedar: HexColor = '#330f1b';
export const dawn: HexColor = '#a3a09d';
export const sandal: HexColor = '#a68e6d';
export const carrara: HexColor = '#f5f4f2';
