import { getOfficeName, officeTypes } from './offices';
import { getProperties } from './properties';

export const keywords = {
	resource: 'recurs',
	office: 'càrrec',
	offices: 'càrrecs',
	card: 'carta',
	subject: 'súbdit',
	subjects: 'súbdits',
	law: 'llei',
	vote: 'votació',
	vigilance: 'vigilància',
	machination: 'maquinació',
	aggression: 'agressió',
	duel: 'Duel',
	exile: 'expulsar',
	exiled: 'expulsat',
	plot: 'complot',
	plots: 'complots',
	execute: 'executar',
	discard: 'descartar',
	exhaust: 'exhaurir',
	disable: 'inhabilitar',
	assets: 'actius',
	secrets: 'secrets',
	objectives: 'objectius',
	tactics: 'tàctiques',
	kingdomStat: 'indicador del regne',
	kingdomStats: 'indicadors del regne',
	assetsBid: "subhasta d'actius",
	assetsMarket: "mercat d'actius",
	lawsPool: 'fila de lleis',
	exhausted: 'exhaurida',
	successionStruggle: 'lluita per la successió',
	augments: 'Augmenta',
	'kingdom-member': undefined,
	'kingdom-members': undefined,
	player: undefined,
	players: undefined,
	visible: undefined,
	hidden: undefined,
	action: undefined,
	secret: undefined,
	crisis: undefined,
	reaction: undefined,
	constant: undefined,
	...Object.fromEntries(getProperties().map((property) => [property.id, property.title])),
	...Object.fromEntries(officeTypes.map((type) => [type, getOfficeName(type)]))
};

export type Keyword = keyof typeof keywords;
